# Generated by Django 4.0 on 2021-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_countrydata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Brand Population Data',
            },
        ),
        migrations.DeleteModel(
            name='CountryData',
        ),
    ]
