# Generated by Django 4.0 on 2021-12-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_branddata_delete_countrydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branddata',
            old_name='population',
            new_name='rise',
        ),
        migrations.AlterField(
            model_name='branddata',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
