# Generated by Django 4.0.2 on 2022-04-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_population_branddata_rise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'notebooks',
            },
        ),
    ]
